# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 531)
        MainWindow.setMinimumSize(QtCore.QSize(831, 531))
        MainWindow.setMaximumSize(QtCore.QSize(831, 531))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 811, 471))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(428, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 185, 351))
        font = QtGui.QFont()
        font.setItalic(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.suppremer1 = QtWidgets.QPushButton(self.groupBox_2)
        self.suppremer1.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.suppremer1.setObjectName("suppremer1")
        self.gridLayout_2.addWidget(self.suppremer1, 3, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.calculer1 = QtWidgets.QPushButton(self.groupBox_2)
        self.calculer1.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.calculer1.setObjectName("calculer1")
        self.gridLayout_2.addWidget(self.calculer1, 2, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(158, 168, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 2)
        self.lineEdit_Nrejet = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Nrejet.setStyleSheet("background-color: rgb(255, 239, 197);")
        self.lineEdit_Nrejet.setObjectName("lineEdit_Nrejet")
        self.gridLayout_2.addWidget(self.lineEdit_Nrejet, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(200, 10, 571, 351))
        font = QtGui.QFont()
        font.setItalic(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("color: rgb(0, 0, 0);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 185, 351))
        font = QtGui.QFont()
        font.setItalic(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.suppremer2 = QtWidgets.QPushButton(self.groupBox_4)
        self.suppremer2.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.suppremer2.setShortcut("")
        self.suppremer2.setObjectName("suppremer2")
        self.gridLayout_3.addWidget(self.suppremer2, 3, 0, 1, 2)
        self.calculer2 = QtWidgets.QPushButton(self.groupBox_4)
        self.calculer2.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.calculer2.setObjectName("calculer2")
        self.gridLayout_3.addWidget(self.calculer2, 2, 0, 1, 2)
        self.lineEdit_Nintegral = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_Nintegral.setStyleSheet("background-color: rgb(255, 239, 197);")
        self.lineEdit_Nintegral.setObjectName("lineEdit_Nintegral")
        self.gridLayout_3.addWidget(self.lineEdit_Nintegral, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(158, 168, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(200, 10, 571, 351))
        font = QtGui.QFont()
        font.setItalic(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_5)
        font = QtGui.QFont()
        font.setItalic(True)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 183, 351))
        font = QtGui.QFont()
        font.setItalic(True)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_buffon = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_buffon.setStyleSheet("background-color: rgb(255, 239, 197);")
        self.lineEdit_buffon.setObjectName("lineEdit_buffon")
        self.gridLayout_6.addWidget(self.lineEdit_buffon, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(158, 168, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 3, 0, 1, 2)
        self.suppremer2_2 = QtWidgets.QPushButton(self.groupBox_6)
        self.suppremer2_2.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.suppremer2_2.setShortcut("")
        self.suppremer2_2.setObjectName("suppremer2_2")
        self.gridLayout_6.addWidget(self.suppremer2_2, 5, 0, 1, 2)
        self.lineEdit_d = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_d.setStyleSheet("background-color: rgb(255, 239, 197);")
        self.lineEdit_d.setObjectName("lineEdit_d")
        self.gridLayout_6.addWidget(self.lineEdit_d, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 2, 0, 1, 1)
        self.calculer2_2 = QtWidgets.QPushButton(self.groupBox_6)
        self.calculer2_2.setStyleSheet("background-color: rgb(252, 175, 62);")
        self.calculer2_2.setObjectName("calculer2_2")
        self.gridLayout_6.addWidget(self.calculer2_2, 4, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEdit_a = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_a.setStyleSheet("background-color: rgb(255, 239, 197);")
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.gridLayout_6.addWidget(self.lineEdit_a, 1, 1, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setGeometry(QtCore.QRect(200, 10, 571, 351))
        font = QtGui.QFont()
        font.setItalic(True)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_7)
        font = QtGui.QFont()
        font.setItalic(True)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_7.addWidget(self.tableWidget_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_5.addWidget(self.tabWidget, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.menuMenu.setFont(font)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calcul de Pi par MC -v1.0"))
        self.groupBox.setTitle(_translate("MainWindow", "Calcule De Pi"))
        self.label_3.setText(_translate("MainWindow", "Pi Exacte"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Les Données"))
        self.suppremer1.setText(_translate("MainWindow", "Supprimer"))
        self.label.setText(_translate("MainWindow", "N"))
        self.calculer1.setText(_translate("MainWindow", "Calculer"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Resultas"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "N (échantillon)"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Pi Calculer"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Erreur"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "    Méthode de Rejet    "))
        self.groupBox_4.setTitle(_translate("MainWindow", "Les Données"))
        self.suppremer2.setText(_translate("MainWindow", "Supprimer"))
        self.calculer2.setText(_translate("MainWindow", "Calculer"))
        self.label_2.setText(_translate("MainWindow", "N"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Resultas"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "N (échantillon)"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Pi Calculer"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Erreur"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "    Méthode de l\'intégral    "))
        self.groupBox_6.setTitle(_translate("MainWindow", "Les Données"))
        self.suppremer2_2.setText(_translate("MainWindow", "Supprimer"))
        self.label_5.setText(_translate("MainWindow", "D"))
        self.label_4.setText(_translate("MainWindow", "N"))
        self.calculer2_2.setText(_translate("MainWindow", "Calculer"))
        self.label_6.setText(_translate("MainWindow", "a"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Resultas"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "N (échantillon)"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Pi Calculer"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Erreur"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "    Méthode de Bufon    "))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

